---
default_stages: [commit]
exclude: vale/styles/*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=no]
      - id: check-added-large-files
        args: [--maxkb=10240]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        name: Prettier

  - repo: local
    hooks:
      - id: dockerfile-provides-entrypoint
        name: Vale
        language: docker_image
        entry: jdkato/vale:latest
